apiVersion: v1
kind: Service
metadata:
  name: http-forwarder
spec:
  ports:
    - port: 13734
  selector:
    app: http-forwarder
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-forwarder
spec:
  selector:
    matchLabels:
      app: http-forwarder
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: http-forwarder
    spec:
      containers:
        - image: docker.io/karolisr/http-forwarder:latest          
          name: http-forwarder
          ports:
            - containerPort: 13734
              name: http-forwarder
